version: '3'

networks:
  rabbitMQ:
    name: topic_rabbitMQ
    external: true
    driver: bridge
  mongo:
  backend:
    name: topic_backend
    external: true
    driver: bridge
  subject:
    name: subject_service
    driver: bridge
    external: true
  
services:
  backend:
    image: polapob/topic-service:2.0
    ports:
      - 4000:4000
    container_name: topic-backend
    restart: always
    networks:
      - mongo
      - rabbitMQ
      - subject

  mongo:
    image: mongo:7.0.1
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: post
      MONGO_INIT_DB_USERNAME: poom
      MONGO_INIT_DB_PASSWORD: poom

    volumes:
      - /Users/polapob/Downloads/first/data/db:/data/db
    networks:
      - mongo

  mongo-express:
    image: mongo-express:1.0.0-alpha
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - mongo