// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subject.proto

package org.example;

public interface CreateSubjectRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:subject.CreateSubjectRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string subject_id = 1;</code>
   * @return The subjectId.
   */
  java.lang.String getSubjectId();
  /**
   * <code>string subject_id = 1;</code>
   * @return The bytes for subjectId.
   */
  com.google.protobuf.ByteString
      getSubjectIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int64 semester = 3;</code>
   * @return The semester.
   */
  long getSemester();

  /**
   * <code>int64 year = 4;</code>
   * @return The year.
   */
  long getYear();

  /**
   * <code>string faculty = 5;</code>
   * @return The faculty.
   */
  java.lang.String getFaculty();
  /**
   * <code>string faculty = 5;</code>
   * @return The bytes for faculty.
   */
  com.google.protobuf.ByteString
      getFacultyBytes();

  /**
   * <code>string description = 6;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 6;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>bool is_admin = 99;</code>
   * @return The isAdmin.
   */
  boolean getIsAdmin();
}
