// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subject.proto

package org.example;

public interface CreateSectionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:subject.CreateSectionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 subject_id = 1;</code>
   * @return The subjectId.
   */
  long getSubjectId();

  /**
   * <code>int64 number = 2;</code>
   * @return The number.
   */
  long getNumber();

  /**
   * <code>string description = 3;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>bool is_admin = 99;</code>
   * @return The isAdmin.
   */
  boolean getIsAdmin();
}
