// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: instructor.proto

package org.example;

/**
 * Protobuf type {@code subject.CreateInstructorResponse}
 */
public final class CreateInstructorResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:subject.CreateInstructorResponse)
    CreateInstructorResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateInstructorResponse.newBuilder() to construct.
  private CreateInstructorResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateInstructorResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateInstructorResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.Instructor.internal_static_subject_CreateInstructorResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.Instructor.internal_static_subject_CreateInstructorResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.CreateInstructorResponse.class, org.example.CreateInstructorResponse.Builder.class);
  }

  private int bitField0_;
  public static final int INSTRUCTOR_FIELD_NUMBER = 1;
  private org.example.Entity.Instructor instructor_;
  /**
   * <code>.subject.Instructor instructor = 1;</code>
   * @return Whether the instructor field is set.
   */
  @java.lang.Override
  public boolean hasInstructor() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.subject.Instructor instructor = 1;</code>
   * @return The instructor.
   */
  @java.lang.Override
  public org.example.Entity.Instructor getInstructor() {
    return instructor_ == null ? org.example.Entity.Instructor.getDefaultInstance() : instructor_;
  }
  /**
   * <code>.subject.Instructor instructor = 1;</code>
   */
  @java.lang.Override
  public org.example.Entity.InstructorOrBuilder getInstructorOrBuilder() {
    return instructor_ == null ? org.example.Entity.Instructor.getDefaultInstance() : instructor_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getInstructor());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getInstructor());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.CreateInstructorResponse)) {
      return super.equals(obj);
    }
    org.example.CreateInstructorResponse other = (org.example.CreateInstructorResponse) obj;

    if (hasInstructor() != other.hasInstructor()) return false;
    if (hasInstructor()) {
      if (!getInstructor()
          .equals(other.getInstructor())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasInstructor()) {
      hash = (37 * hash) + INSTRUCTOR_FIELD_NUMBER;
      hash = (53 * hash) + getInstructor().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.CreateInstructorResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.CreateInstructorResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.CreateInstructorResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.CreateInstructorResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.CreateInstructorResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.CreateInstructorResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.CreateInstructorResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.CreateInstructorResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.example.CreateInstructorResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.example.CreateInstructorResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.CreateInstructorResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.CreateInstructorResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.CreateInstructorResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code subject.CreateInstructorResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:subject.CreateInstructorResponse)
      org.example.CreateInstructorResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.Instructor.internal_static_subject_CreateInstructorResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.Instructor.internal_static_subject_CreateInstructorResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.CreateInstructorResponse.class, org.example.CreateInstructorResponse.Builder.class);
    }

    // Construct using org.example.CreateInstructorResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getInstructorFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      instructor_ = null;
      if (instructorBuilder_ != null) {
        instructorBuilder_.dispose();
        instructorBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.Instructor.internal_static_subject_CreateInstructorResponse_descriptor;
    }

    @java.lang.Override
    public org.example.CreateInstructorResponse getDefaultInstanceForType() {
      return org.example.CreateInstructorResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.CreateInstructorResponse build() {
      org.example.CreateInstructorResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.CreateInstructorResponse buildPartial() {
      org.example.CreateInstructorResponse result = new org.example.CreateInstructorResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.example.CreateInstructorResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.instructor_ = instructorBuilder_ == null
            ? instructor_
            : instructorBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.CreateInstructorResponse) {
        return mergeFrom((org.example.CreateInstructorResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.CreateInstructorResponse other) {
      if (other == org.example.CreateInstructorResponse.getDefaultInstance()) return this;
      if (other.hasInstructor()) {
        mergeInstructor(other.getInstructor());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getInstructorFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private org.example.Entity.Instructor instructor_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.example.Entity.Instructor, org.example.Entity.Instructor.Builder, org.example.Entity.InstructorOrBuilder> instructorBuilder_;
    /**
     * <code>.subject.Instructor instructor = 1;</code>
     * @return Whether the instructor field is set.
     */
    public boolean hasInstructor() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.subject.Instructor instructor = 1;</code>
     * @return The instructor.
     */
    public org.example.Entity.Instructor getInstructor() {
      if (instructorBuilder_ == null) {
        return instructor_ == null ? org.example.Entity.Instructor.getDefaultInstance() : instructor_;
      } else {
        return instructorBuilder_.getMessage();
      }
    }
    /**
     * <code>.subject.Instructor instructor = 1;</code>
     */
    public Builder setInstructor(org.example.Entity.Instructor value) {
      if (instructorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        instructor_ = value;
      } else {
        instructorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.subject.Instructor instructor = 1;</code>
     */
    public Builder setInstructor(
        org.example.Entity.Instructor.Builder builderForValue) {
      if (instructorBuilder_ == null) {
        instructor_ = builderForValue.build();
      } else {
        instructorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.subject.Instructor instructor = 1;</code>
     */
    public Builder mergeInstructor(org.example.Entity.Instructor value) {
      if (instructorBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          instructor_ != null &&
          instructor_ != org.example.Entity.Instructor.getDefaultInstance()) {
          getInstructorBuilder().mergeFrom(value);
        } else {
          instructor_ = value;
        }
      } else {
        instructorBuilder_.mergeFrom(value);
      }
      if (instructor_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.subject.Instructor instructor = 1;</code>
     */
    public Builder clearInstructor() {
      bitField0_ = (bitField0_ & ~0x00000001);
      instructor_ = null;
      if (instructorBuilder_ != null) {
        instructorBuilder_.dispose();
        instructorBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.subject.Instructor instructor = 1;</code>
     */
    public org.example.Entity.Instructor.Builder getInstructorBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getInstructorFieldBuilder().getBuilder();
    }
    /**
     * <code>.subject.Instructor instructor = 1;</code>
     */
    public org.example.Entity.InstructorOrBuilder getInstructorOrBuilder() {
      if (instructorBuilder_ != null) {
        return instructorBuilder_.getMessageOrBuilder();
      } else {
        return instructor_ == null ?
            org.example.Entity.Instructor.getDefaultInstance() : instructor_;
      }
    }
    /**
     * <code>.subject.Instructor instructor = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.example.Entity.Instructor, org.example.Entity.Instructor.Builder, org.example.Entity.InstructorOrBuilder> 
        getInstructorFieldBuilder() {
      if (instructorBuilder_ == null) {
        instructorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.example.Entity.Instructor, org.example.Entity.Instructor.Builder, org.example.Entity.InstructorOrBuilder>(
                getInstructor(),
                getParentForChildren(),
                isClean());
        instructor_ = null;
      }
      return instructorBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:subject.CreateInstructorResponse)
  }

  // @@protoc_insertion_point(class_scope:subject.CreateInstructorResponse)
  private static final org.example.CreateInstructorResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.CreateInstructorResponse();
  }

  public static org.example.CreateInstructorResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateInstructorResponse>
      PARSER = new com.google.protobuf.AbstractParser<CreateInstructorResponse>() {
    @java.lang.Override
    public CreateInstructorResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateInstructorResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateInstructorResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.CreateInstructorResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

