// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: instructor.proto

package org.example;

public interface DeleteInstructorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:subject.DeleteInstructorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>bool is_admin = 99;</code>
   * @return The isAdmin.
   */
  boolean getIsAdmin();
}
