// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subject.proto

package org.example;

public interface DeleteSectionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:subject.DeleteSectionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.subject.Section section = 1;</code>
   * @return Whether the section field is set.
   */
  boolean hasSection();
  /**
   * <code>.subject.Section section = 1;</code>
   * @return The section.
   */
  org.example.Entity.Section getSection();
  /**
   * <code>.subject.Section section = 1;</code>
   */
  org.example.Entity.SectionOrBuilder getSectionOrBuilder();
}
