// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: instructor.proto

package org.example;

public interface GetInstructorbyIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:subject.GetInstructorbyIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
