// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subject.proto

package org.example;

public interface GetSubjectByIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:subject.GetSubjectByIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
