// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: instructor.proto

package org.example;

public final class Instructor {
  private Instructor() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_subject_PaginateInstructorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_subject_PaginateInstructorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_subject_PaginateInstructorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_subject_PaginateInstructorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_subject_GetInstructorbyIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_subject_GetInstructorbyIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_subject_GetInstructorbyIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_subject_GetInstructorbyIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_subject_CreateInstructorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_subject_CreateInstructorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_subject_CreateInstructorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_subject_CreateInstructorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_subject_UpdateInstructorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_subject_UpdateInstructorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_subject_UpdateInstructorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_subject_UpdateInstructorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_subject_DeleteInstructorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_subject_DeleteInstructorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_subject_DeleteInstructorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_subject_DeleteInstructorResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020instructor.proto\022\007subject\032\014entity.prot" +
      "o\"O\n\031PaginateInstructorRequest\022\023\n\013page_n" +
      "umber\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\017\n\007faculty\030\003 \001" +
      "(\t\"\236\001\n\032PaginateInstructorResponse\022\023\n\013pag" +
      "e_number\030\001 \001(\003\022\020\n\010per_page\030\002 \001(\003\022\022\n\npage" +
      "_count\030\003 \001(\003\022\023\n\013total_count\030\004 \001(\003\0220\n\013ins" +
      "tructors\030\005 \003(\0132\033.subject.InstructorMetad" +
      "ata\"&\n\030GetInstructorbyIdRequest\022\n\n\002id\030\001 " +
      "\001(\003\"D\n\031GetInstructorbyIdResponse\022\'\n\ninst" +
      "ructor\030\001 \001(\0132\023.subject.Instructor\"\225\001\n\027Cr" +
      "eateInstructorRequest\022\021\n\tfull_name\030\002 \001(\t" +
      "\022\017\n\007faculty\030\003 \001(\t\022\r\n\005email\030\004 \001(\t\022\024\n\014phon" +
      "e_number\030\005 \001(\t\022\017\n\007website\030\006 \001(\t\022\016\n\006degre" +
      "e\030\007 \001(\t\022\020\n\010is_admin\030c \001(\010\"C\n\030CreateInstr" +
      "uctorResponse\022\'\n\ninstructor\030\001 \001(\0132\023.subj" +
      "ect.Instructor\"\241\001\n\027UpdateInstructorReque" +
      "st\022\n\n\002id\030\001 \001(\003\022\021\n\tfull_name\030\002 \001(\t\022\017\n\007fac" +
      "ulty\030\003 \001(\t\022\r\n\005email\030\004 \001(\t\022\024\n\014phone_numbe" +
      "r\030\005 \001(\t\022\017\n\007website\030\006 \001(\t\022\016\n\006degree\030\007 \001(\t" +
      "\022\020\n\010is_admin\030c \001(\010\"C\n\030UpdateInstructorRe" +
      "sponse\022\'\n\ninstructor\030\001 \001(\0132\023.subject.Ins" +
      "tructor\"7\n\027DeleteInstructorRequest\022\n\n\002id" +
      "\030\001 \001(\003\022\020\n\010is_admin\030c \001(\010\"C\n\030DeleteInstru" +
      "ctorResponse\022\'\n\ninstructor\030\001 \001(\0132\023.subje" +
      "ct.Instructor2\331\003\n\021InstructorService\022]\n\022P" +
      "aginateInstructor\022\".subject.PaginateInst" +
      "ructorRequest\032#.subject.PaginateInstruct" +
      "orResponse\022Z\n\021GetInstructorbyId\022!.subjec" +
      "t.GetInstructorbyIdRequest\032\".subject.Get" +
      "InstructorbyIdResponse\022W\n\020CreateInstruct" +
      "or\022 .subject.CreateInstructorRequest\032!.s" +
      "ubject.CreateInstructorResponse\022W\n\020Updat" +
      "eInstructor\022 .subject.UpdateInstructorRe" +
      "quest\032!.subject.UpdateInstructorResponse" +
      "\022W\n\020DeleteInstructor\022 .subject.DeleteIns" +
      "tructorRequest\032!.subject.DeleteInstructo" +
      "rResponseB\017\n\013org.exampleP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.example.Entity.getDescriptor(),
        });
    internal_static_subject_PaginateInstructorRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_subject_PaginateInstructorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_subject_PaginateInstructorRequest_descriptor,
        new java.lang.String[] { "PageNumber", "Name", "Faculty", });
    internal_static_subject_PaginateInstructorResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_subject_PaginateInstructorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_subject_PaginateInstructorResponse_descriptor,
        new java.lang.String[] { "PageNumber", "PerPage", "PageCount", "TotalCount", "Instructors", });
    internal_static_subject_GetInstructorbyIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_subject_GetInstructorbyIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_subject_GetInstructorbyIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_subject_GetInstructorbyIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_subject_GetInstructorbyIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_subject_GetInstructorbyIdResponse_descriptor,
        new java.lang.String[] { "Instructor", });
    internal_static_subject_CreateInstructorRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_subject_CreateInstructorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_subject_CreateInstructorRequest_descriptor,
        new java.lang.String[] { "FullName", "Faculty", "Email", "PhoneNumber", "Website", "Degree", "IsAdmin", });
    internal_static_subject_CreateInstructorResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_subject_CreateInstructorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_subject_CreateInstructorResponse_descriptor,
        new java.lang.String[] { "Instructor", });
    internal_static_subject_UpdateInstructorRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_subject_UpdateInstructorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_subject_UpdateInstructorRequest_descriptor,
        new java.lang.String[] { "Id", "FullName", "Faculty", "Email", "PhoneNumber", "Website", "Degree", "IsAdmin", });
    internal_static_subject_UpdateInstructorResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_subject_UpdateInstructorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_subject_UpdateInstructorResponse_descriptor,
        new java.lang.String[] { "Instructor", });
    internal_static_subject_DeleteInstructorRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_subject_DeleteInstructorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_subject_DeleteInstructorRequest_descriptor,
        new java.lang.String[] { "Id", "IsAdmin", });
    internal_static_subject_DeleteInstructorResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_subject_DeleteInstructorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_subject_DeleteInstructorResponse_descriptor,
        new java.lang.String[] { "Instructor", });
    org.example.Entity.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
