// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subject.proto

package org.example;

public interface PaginateFileBySubjectResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:subject.PaginateFileBySubjectResponse)
    com.google.protobuf.MessageOrBuilder {
}
