// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subject.proto

package org.example;

public interface PaginateSubjectResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:subject.PaginateSubjectResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 page_number = 1;</code>
   * @return The pageNumber.
   */
  long getPageNumber();

  /**
   * <code>int64 per_page = 2;</code>
   * @return The perPage.
   */
  long getPerPage();

  /**
   * <code>int64 page_count = 3;</code>
   * @return The pageCount.
   */
  long getPageCount();

  /**
   * <code>int64 total_count = 4;</code>
   * @return The totalCount.
   */
  long getTotalCount();

  /**
   * <code>repeated .subject.SubjectMetadata subjects = 5;</code>
   */
  java.util.List<org.example.Entity.SubjectMetadata> 
      getSubjectsList();
  /**
   * <code>repeated .subject.SubjectMetadata subjects = 5;</code>
   */
  org.example.Entity.SubjectMetadata getSubjects(int index);
  /**
   * <code>repeated .subject.SubjectMetadata subjects = 5;</code>
   */
  int getSubjectsCount();
  /**
   * <code>repeated .subject.SubjectMetadata subjects = 5;</code>
   */
  java.util.List<? extends org.example.Entity.SubjectMetadataOrBuilder> 
      getSubjectsOrBuilderList();
  /**
   * <code>repeated .subject.SubjectMetadata subjects = 5;</code>
   */
  org.example.Entity.SubjectMetadataOrBuilder getSubjectsOrBuilder(
      int index);
}
