// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subject.proto

package org.example;

public interface PaginatePostBySubjectRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:subject.PaginatePostBySubjectRequest)
    com.google.protobuf.MessageOrBuilder {
}
