// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subject.proto

package org.example;

/**
 * Protobuf type {@code subject.PaginateSubjectResponse}
 */
public final class PaginateSubjectResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:subject.PaginateSubjectResponse)
    PaginateSubjectResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PaginateSubjectResponse.newBuilder() to construct.
  private PaginateSubjectResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PaginateSubjectResponse() {
    subjects_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PaginateSubjectResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.Subject.internal_static_subject_PaginateSubjectResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.Subject.internal_static_subject_PaginateSubjectResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.PaginateSubjectResponse.class, org.example.PaginateSubjectResponse.Builder.class);
  }

  public static final int PAGE_NUMBER_FIELD_NUMBER = 1;
  private long pageNumber_ = 0L;
  /**
   * <code>int64 page_number = 1;</code>
   * @return The pageNumber.
   */
  @java.lang.Override
  public long getPageNumber() {
    return pageNumber_;
  }

  public static final int PER_PAGE_FIELD_NUMBER = 2;
  private long perPage_ = 0L;
  /**
   * <code>int64 per_page = 2;</code>
   * @return The perPage.
   */
  @java.lang.Override
  public long getPerPage() {
    return perPage_;
  }

  public static final int PAGE_COUNT_FIELD_NUMBER = 3;
  private long pageCount_ = 0L;
  /**
   * <code>int64 page_count = 3;</code>
   * @return The pageCount.
   */
  @java.lang.Override
  public long getPageCount() {
    return pageCount_;
  }

  public static final int TOTAL_COUNT_FIELD_NUMBER = 4;
  private long totalCount_ = 0L;
  /**
   * <code>int64 total_count = 4;</code>
   * @return The totalCount.
   */
  @java.lang.Override
  public long getTotalCount() {
    return totalCount_;
  }

  public static final int SUBJECTS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<org.example.Entity.SubjectMetadata> subjects_;
  /**
   * <code>repeated .subject.SubjectMetadata subjects = 5;</code>
   */
  @java.lang.Override
  public java.util.List<org.example.Entity.SubjectMetadata> getSubjectsList() {
    return subjects_;
  }
  /**
   * <code>repeated .subject.SubjectMetadata subjects = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.example.Entity.SubjectMetadataOrBuilder> 
      getSubjectsOrBuilderList() {
    return subjects_;
  }
  /**
   * <code>repeated .subject.SubjectMetadata subjects = 5;</code>
   */
  @java.lang.Override
  public int getSubjectsCount() {
    return subjects_.size();
  }
  /**
   * <code>repeated .subject.SubjectMetadata subjects = 5;</code>
   */
  @java.lang.Override
  public org.example.Entity.SubjectMetadata getSubjects(int index) {
    return subjects_.get(index);
  }
  /**
   * <code>repeated .subject.SubjectMetadata subjects = 5;</code>
   */
  @java.lang.Override
  public org.example.Entity.SubjectMetadataOrBuilder getSubjectsOrBuilder(
      int index) {
    return subjects_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (pageNumber_ != 0L) {
      output.writeInt64(1, pageNumber_);
    }
    if (perPage_ != 0L) {
      output.writeInt64(2, perPage_);
    }
    if (pageCount_ != 0L) {
      output.writeInt64(3, pageCount_);
    }
    if (totalCount_ != 0L) {
      output.writeInt64(4, totalCount_);
    }
    for (int i = 0; i < subjects_.size(); i++) {
      output.writeMessage(5, subjects_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (pageNumber_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, pageNumber_);
    }
    if (perPage_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, perPage_);
    }
    if (pageCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, pageCount_);
    }
    if (totalCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, totalCount_);
    }
    for (int i = 0; i < subjects_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, subjects_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.PaginateSubjectResponse)) {
      return super.equals(obj);
    }
    org.example.PaginateSubjectResponse other = (org.example.PaginateSubjectResponse) obj;

    if (getPageNumber()
        != other.getPageNumber()) return false;
    if (getPerPage()
        != other.getPerPage()) return false;
    if (getPageCount()
        != other.getPageCount()) return false;
    if (getTotalCount()
        != other.getTotalCount()) return false;
    if (!getSubjectsList()
        .equals(other.getSubjectsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PAGE_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPageNumber());
    hash = (37 * hash) + PER_PAGE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPerPage());
    hash = (37 * hash) + PAGE_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPageCount());
    hash = (37 * hash) + TOTAL_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalCount());
    if (getSubjectsCount() > 0) {
      hash = (37 * hash) + SUBJECTS_FIELD_NUMBER;
      hash = (53 * hash) + getSubjectsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.PaginateSubjectResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.PaginateSubjectResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.PaginateSubjectResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.PaginateSubjectResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.PaginateSubjectResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.PaginateSubjectResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.PaginateSubjectResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.PaginateSubjectResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.example.PaginateSubjectResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.example.PaginateSubjectResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.PaginateSubjectResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.PaginateSubjectResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.PaginateSubjectResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code subject.PaginateSubjectResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:subject.PaginateSubjectResponse)
      org.example.PaginateSubjectResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.Subject.internal_static_subject_PaginateSubjectResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.Subject.internal_static_subject_PaginateSubjectResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.PaginateSubjectResponse.class, org.example.PaginateSubjectResponse.Builder.class);
    }

    // Construct using org.example.PaginateSubjectResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      pageNumber_ = 0L;
      perPage_ = 0L;
      pageCount_ = 0L;
      totalCount_ = 0L;
      if (subjectsBuilder_ == null) {
        subjects_ = java.util.Collections.emptyList();
      } else {
        subjects_ = null;
        subjectsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.Subject.internal_static_subject_PaginateSubjectResponse_descriptor;
    }

    @java.lang.Override
    public org.example.PaginateSubjectResponse getDefaultInstanceForType() {
      return org.example.PaginateSubjectResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.PaginateSubjectResponse build() {
      org.example.PaginateSubjectResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.PaginateSubjectResponse buildPartial() {
      org.example.PaginateSubjectResponse result = new org.example.PaginateSubjectResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.example.PaginateSubjectResponse result) {
      if (subjectsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          subjects_ = java.util.Collections.unmodifiableList(subjects_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.subjects_ = subjects_;
      } else {
        result.subjects_ = subjectsBuilder_.build();
      }
    }

    private void buildPartial0(org.example.PaginateSubjectResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.pageNumber_ = pageNumber_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.perPage_ = perPage_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.pageCount_ = pageCount_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.totalCount_ = totalCount_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.PaginateSubjectResponse) {
        return mergeFrom((org.example.PaginateSubjectResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.PaginateSubjectResponse other) {
      if (other == org.example.PaginateSubjectResponse.getDefaultInstance()) return this;
      if (other.getPageNumber() != 0L) {
        setPageNumber(other.getPageNumber());
      }
      if (other.getPerPage() != 0L) {
        setPerPage(other.getPerPage());
      }
      if (other.getPageCount() != 0L) {
        setPageCount(other.getPageCount());
      }
      if (other.getTotalCount() != 0L) {
        setTotalCount(other.getTotalCount());
      }
      if (subjectsBuilder_ == null) {
        if (!other.subjects_.isEmpty()) {
          if (subjects_.isEmpty()) {
            subjects_ = other.subjects_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureSubjectsIsMutable();
            subjects_.addAll(other.subjects_);
          }
          onChanged();
        }
      } else {
        if (!other.subjects_.isEmpty()) {
          if (subjectsBuilder_.isEmpty()) {
            subjectsBuilder_.dispose();
            subjectsBuilder_ = null;
            subjects_ = other.subjects_;
            bitField0_ = (bitField0_ & ~0x00000010);
            subjectsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSubjectsFieldBuilder() : null;
          } else {
            subjectsBuilder_.addAllMessages(other.subjects_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              pageNumber_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              perPage_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              pageCount_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              totalCount_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              org.example.Entity.SubjectMetadata m =
                  input.readMessage(
                      org.example.Entity.SubjectMetadata.parser(),
                      extensionRegistry);
              if (subjectsBuilder_ == null) {
                ensureSubjectsIsMutable();
                subjects_.add(m);
              } else {
                subjectsBuilder_.addMessage(m);
              }
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long pageNumber_ ;
    /**
     * <code>int64 page_number = 1;</code>
     * @return The pageNumber.
     */
    @java.lang.Override
    public long getPageNumber() {
      return pageNumber_;
    }
    /**
     * <code>int64 page_number = 1;</code>
     * @param value The pageNumber to set.
     * @return This builder for chaining.
     */
    public Builder setPageNumber(long value) {

      pageNumber_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 page_number = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPageNumber() {
      bitField0_ = (bitField0_ & ~0x00000001);
      pageNumber_ = 0L;
      onChanged();
      return this;
    }

    private long perPage_ ;
    /**
     * <code>int64 per_page = 2;</code>
     * @return The perPage.
     */
    @java.lang.Override
    public long getPerPage() {
      return perPage_;
    }
    /**
     * <code>int64 per_page = 2;</code>
     * @param value The perPage to set.
     * @return This builder for chaining.
     */
    public Builder setPerPage(long value) {

      perPage_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 per_page = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPerPage() {
      bitField0_ = (bitField0_ & ~0x00000002);
      perPage_ = 0L;
      onChanged();
      return this;
    }

    private long pageCount_ ;
    /**
     * <code>int64 page_count = 3;</code>
     * @return The pageCount.
     */
    @java.lang.Override
    public long getPageCount() {
      return pageCount_;
    }
    /**
     * <code>int64 page_count = 3;</code>
     * @param value The pageCount to set.
     * @return This builder for chaining.
     */
    public Builder setPageCount(long value) {

      pageCount_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 page_count = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPageCount() {
      bitField0_ = (bitField0_ & ~0x00000004);
      pageCount_ = 0L;
      onChanged();
      return this;
    }

    private long totalCount_ ;
    /**
     * <code>int64 total_count = 4;</code>
     * @return The totalCount.
     */
    @java.lang.Override
    public long getTotalCount() {
      return totalCount_;
    }
    /**
     * <code>int64 total_count = 4;</code>
     * @param value The totalCount to set.
     * @return This builder for chaining.
     */
    public Builder setTotalCount(long value) {

      totalCount_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int64 total_count = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalCount() {
      bitField0_ = (bitField0_ & ~0x00000008);
      totalCount_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<org.example.Entity.SubjectMetadata> subjects_ =
      java.util.Collections.emptyList();
    private void ensureSubjectsIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        subjects_ = new java.util.ArrayList<org.example.Entity.SubjectMetadata>(subjects_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.example.Entity.SubjectMetadata, org.example.Entity.SubjectMetadata.Builder, org.example.Entity.SubjectMetadataOrBuilder> subjectsBuilder_;

    /**
     * <code>repeated .subject.SubjectMetadata subjects = 5;</code>
     */
    public java.util.List<org.example.Entity.SubjectMetadata> getSubjectsList() {
      if (subjectsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(subjects_);
      } else {
        return subjectsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .subject.SubjectMetadata subjects = 5;</code>
     */
    public int getSubjectsCount() {
      if (subjectsBuilder_ == null) {
        return subjects_.size();
      } else {
        return subjectsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .subject.SubjectMetadata subjects = 5;</code>
     */
    public org.example.Entity.SubjectMetadata getSubjects(int index) {
      if (subjectsBuilder_ == null) {
        return subjects_.get(index);
      } else {
        return subjectsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .subject.SubjectMetadata subjects = 5;</code>
     */
    public Builder setSubjects(
        int index, org.example.Entity.SubjectMetadata value) {
      if (subjectsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSubjectsIsMutable();
        subjects_.set(index, value);
        onChanged();
      } else {
        subjectsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .subject.SubjectMetadata subjects = 5;</code>
     */
    public Builder setSubjects(
        int index, org.example.Entity.SubjectMetadata.Builder builderForValue) {
      if (subjectsBuilder_ == null) {
        ensureSubjectsIsMutable();
        subjects_.set(index, builderForValue.build());
        onChanged();
      } else {
        subjectsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .subject.SubjectMetadata subjects = 5;</code>
     */
    public Builder addSubjects(org.example.Entity.SubjectMetadata value) {
      if (subjectsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSubjectsIsMutable();
        subjects_.add(value);
        onChanged();
      } else {
        subjectsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .subject.SubjectMetadata subjects = 5;</code>
     */
    public Builder addSubjects(
        int index, org.example.Entity.SubjectMetadata value) {
      if (subjectsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSubjectsIsMutable();
        subjects_.add(index, value);
        onChanged();
      } else {
        subjectsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .subject.SubjectMetadata subjects = 5;</code>
     */
    public Builder addSubjects(
        org.example.Entity.SubjectMetadata.Builder builderForValue) {
      if (subjectsBuilder_ == null) {
        ensureSubjectsIsMutable();
        subjects_.add(builderForValue.build());
        onChanged();
      } else {
        subjectsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .subject.SubjectMetadata subjects = 5;</code>
     */
    public Builder addSubjects(
        int index, org.example.Entity.SubjectMetadata.Builder builderForValue) {
      if (subjectsBuilder_ == null) {
        ensureSubjectsIsMutable();
        subjects_.add(index, builderForValue.build());
        onChanged();
      } else {
        subjectsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .subject.SubjectMetadata subjects = 5;</code>
     */
    public Builder addAllSubjects(
        java.lang.Iterable<? extends org.example.Entity.SubjectMetadata> values) {
      if (subjectsBuilder_ == null) {
        ensureSubjectsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, subjects_);
        onChanged();
      } else {
        subjectsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .subject.SubjectMetadata subjects = 5;</code>
     */
    public Builder clearSubjects() {
      if (subjectsBuilder_ == null) {
        subjects_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        subjectsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .subject.SubjectMetadata subjects = 5;</code>
     */
    public Builder removeSubjects(int index) {
      if (subjectsBuilder_ == null) {
        ensureSubjectsIsMutable();
        subjects_.remove(index);
        onChanged();
      } else {
        subjectsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .subject.SubjectMetadata subjects = 5;</code>
     */
    public org.example.Entity.SubjectMetadata.Builder getSubjectsBuilder(
        int index) {
      return getSubjectsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .subject.SubjectMetadata subjects = 5;</code>
     */
    public org.example.Entity.SubjectMetadataOrBuilder getSubjectsOrBuilder(
        int index) {
      if (subjectsBuilder_ == null) {
        return subjects_.get(index);  } else {
        return subjectsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .subject.SubjectMetadata subjects = 5;</code>
     */
    public java.util.List<? extends org.example.Entity.SubjectMetadataOrBuilder> 
         getSubjectsOrBuilderList() {
      if (subjectsBuilder_ != null) {
        return subjectsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(subjects_);
      }
    }
    /**
     * <code>repeated .subject.SubjectMetadata subjects = 5;</code>
     */
    public org.example.Entity.SubjectMetadata.Builder addSubjectsBuilder() {
      return getSubjectsFieldBuilder().addBuilder(
          org.example.Entity.SubjectMetadata.getDefaultInstance());
    }
    /**
     * <code>repeated .subject.SubjectMetadata subjects = 5;</code>
     */
    public org.example.Entity.SubjectMetadata.Builder addSubjectsBuilder(
        int index) {
      return getSubjectsFieldBuilder().addBuilder(
          index, org.example.Entity.SubjectMetadata.getDefaultInstance());
    }
    /**
     * <code>repeated .subject.SubjectMetadata subjects = 5;</code>
     */
    public java.util.List<org.example.Entity.SubjectMetadata.Builder> 
         getSubjectsBuilderList() {
      return getSubjectsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.example.Entity.SubjectMetadata, org.example.Entity.SubjectMetadata.Builder, org.example.Entity.SubjectMetadataOrBuilder> 
        getSubjectsFieldBuilder() {
      if (subjectsBuilder_ == null) {
        subjectsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.example.Entity.SubjectMetadata, org.example.Entity.SubjectMetadata.Builder, org.example.Entity.SubjectMetadataOrBuilder>(
                subjects_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        subjects_ = null;
      }
      return subjectsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:subject.PaginateSubjectResponse)
  }

  // @@protoc_insertion_point(class_scope:subject.PaginateSubjectResponse)
  private static final org.example.PaginateSubjectResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.PaginateSubjectResponse();
  }

  public static org.example.PaginateSubjectResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PaginateSubjectResponse>
      PARSER = new com.google.protobuf.AbstractParser<PaginateSubjectResponse>() {
    @java.lang.Override
    public PaginateSubjectResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PaginateSubjectResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PaginateSubjectResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.PaginateSubjectResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

