// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: instructor.proto

package org.example;

public interface PaginateInstructorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:subject.PaginateInstructorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 page_number = 1;</code>
   * @return The pageNumber.
   */
  long getPageNumber();

  /**
   * <code>int64 per_page = 2;</code>
   * @return The perPage.
   */
  long getPerPage();

  /**
   * <code>int64 page_count = 3;</code>
   * @return The pageCount.
   */
  long getPageCount();

  /**
   * <code>int64 total_count = 4;</code>
   * @return The totalCount.
   */
  long getTotalCount();

  /**
   * <code>repeated .subject.InstructorMetadata instructors = 5;</code>
   */
  java.util.List<org.example.Entity.InstructorMetadata> 
      getInstructorsList();
  /**
   * <code>repeated .subject.InstructorMetadata instructors = 5;</code>
   */
  org.example.Entity.InstructorMetadata getInstructors(int index);
  /**
   * <code>repeated .subject.InstructorMetadata instructors = 5;</code>
   */
  int getInstructorsCount();
  /**
   * <code>repeated .subject.InstructorMetadata instructors = 5;</code>
   */
  java.util.List<? extends org.example.Entity.InstructorMetadataOrBuilder> 
      getInstructorsOrBuilderList();
  /**
   * <code>repeated .subject.InstructorMetadata instructors = 5;</code>
   */
  org.example.Entity.InstructorMetadataOrBuilder getInstructorsOrBuilder(
      int index);
}
