// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: instructor.proto

package org.example;

public interface PaginateInstructorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:subject.PaginateInstructorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 page_number = 1;</code>
   * @return The pageNumber.
   */
  long getPageNumber();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string faculty = 3;</code>
   * @return The faculty.
   */
  java.lang.String getFaculty();
  /**
   * <code>string faculty = 3;</code>
   * @return The bytes for faculty.
   */
  com.google.protobuf.ByteString
      getFacultyBytes();
}
