// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: instructor.proto

package org.example;

/**
 * Protobuf type {@code subject.PaginateInstructorResponse}
 */
public final class PaginateInstructorResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:subject.PaginateInstructorResponse)
    PaginateInstructorResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PaginateInstructorResponse.newBuilder() to construct.
  private PaginateInstructorResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PaginateInstructorResponse() {
    instructors_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PaginateInstructorResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.Instructor.internal_static_subject_PaginateInstructorResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.Instructor.internal_static_subject_PaginateInstructorResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.PaginateInstructorResponse.class, org.example.PaginateInstructorResponse.Builder.class);
  }

  public static final int PAGE_NUMBER_FIELD_NUMBER = 1;
  private long pageNumber_ = 0L;
  /**
   * <code>int64 page_number = 1;</code>
   * @return The pageNumber.
   */
  @java.lang.Override
  public long getPageNumber() {
    return pageNumber_;
  }

  public static final int PER_PAGE_FIELD_NUMBER = 2;
  private long perPage_ = 0L;
  /**
   * <code>int64 per_page = 2;</code>
   * @return The perPage.
   */
  @java.lang.Override
  public long getPerPage() {
    return perPage_;
  }

  public static final int PAGE_COUNT_FIELD_NUMBER = 3;
  private long pageCount_ = 0L;
  /**
   * <code>int64 page_count = 3;</code>
   * @return The pageCount.
   */
  @java.lang.Override
  public long getPageCount() {
    return pageCount_;
  }

  public static final int TOTAL_COUNT_FIELD_NUMBER = 4;
  private long totalCount_ = 0L;
  /**
   * <code>int64 total_count = 4;</code>
   * @return The totalCount.
   */
  @java.lang.Override
  public long getTotalCount() {
    return totalCount_;
  }

  public static final int INSTRUCTORS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<org.example.Entity.InstructorMetadata> instructors_;
  /**
   * <code>repeated .subject.InstructorMetadata instructors = 5;</code>
   */
  @java.lang.Override
  public java.util.List<org.example.Entity.InstructorMetadata> getInstructorsList() {
    return instructors_;
  }
  /**
   * <code>repeated .subject.InstructorMetadata instructors = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.example.Entity.InstructorMetadataOrBuilder> 
      getInstructorsOrBuilderList() {
    return instructors_;
  }
  /**
   * <code>repeated .subject.InstructorMetadata instructors = 5;</code>
   */
  @java.lang.Override
  public int getInstructorsCount() {
    return instructors_.size();
  }
  /**
   * <code>repeated .subject.InstructorMetadata instructors = 5;</code>
   */
  @java.lang.Override
  public org.example.Entity.InstructorMetadata getInstructors(int index) {
    return instructors_.get(index);
  }
  /**
   * <code>repeated .subject.InstructorMetadata instructors = 5;</code>
   */
  @java.lang.Override
  public org.example.Entity.InstructorMetadataOrBuilder getInstructorsOrBuilder(
      int index) {
    return instructors_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (pageNumber_ != 0L) {
      output.writeInt64(1, pageNumber_);
    }
    if (perPage_ != 0L) {
      output.writeInt64(2, perPage_);
    }
    if (pageCount_ != 0L) {
      output.writeInt64(3, pageCount_);
    }
    if (totalCount_ != 0L) {
      output.writeInt64(4, totalCount_);
    }
    for (int i = 0; i < instructors_.size(); i++) {
      output.writeMessage(5, instructors_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (pageNumber_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, pageNumber_);
    }
    if (perPage_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, perPage_);
    }
    if (pageCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, pageCount_);
    }
    if (totalCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, totalCount_);
    }
    for (int i = 0; i < instructors_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, instructors_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.PaginateInstructorResponse)) {
      return super.equals(obj);
    }
    org.example.PaginateInstructorResponse other = (org.example.PaginateInstructorResponse) obj;

    if (getPageNumber()
        != other.getPageNumber()) return false;
    if (getPerPage()
        != other.getPerPage()) return false;
    if (getPageCount()
        != other.getPageCount()) return false;
    if (getTotalCount()
        != other.getTotalCount()) return false;
    if (!getInstructorsList()
        .equals(other.getInstructorsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PAGE_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPageNumber());
    hash = (37 * hash) + PER_PAGE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPerPage());
    hash = (37 * hash) + PAGE_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPageCount());
    hash = (37 * hash) + TOTAL_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalCount());
    if (getInstructorsCount() > 0) {
      hash = (37 * hash) + INSTRUCTORS_FIELD_NUMBER;
      hash = (53 * hash) + getInstructorsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.PaginateInstructorResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.PaginateInstructorResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.PaginateInstructorResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.PaginateInstructorResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.PaginateInstructorResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.PaginateInstructorResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.PaginateInstructorResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.PaginateInstructorResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.example.PaginateInstructorResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.example.PaginateInstructorResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.PaginateInstructorResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.PaginateInstructorResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.PaginateInstructorResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code subject.PaginateInstructorResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:subject.PaginateInstructorResponse)
      org.example.PaginateInstructorResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.Instructor.internal_static_subject_PaginateInstructorResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.Instructor.internal_static_subject_PaginateInstructorResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.PaginateInstructorResponse.class, org.example.PaginateInstructorResponse.Builder.class);
    }

    // Construct using org.example.PaginateInstructorResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      pageNumber_ = 0L;
      perPage_ = 0L;
      pageCount_ = 0L;
      totalCount_ = 0L;
      if (instructorsBuilder_ == null) {
        instructors_ = java.util.Collections.emptyList();
      } else {
        instructors_ = null;
        instructorsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.Instructor.internal_static_subject_PaginateInstructorResponse_descriptor;
    }

    @java.lang.Override
    public org.example.PaginateInstructorResponse getDefaultInstanceForType() {
      return org.example.PaginateInstructorResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.PaginateInstructorResponse build() {
      org.example.PaginateInstructorResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.PaginateInstructorResponse buildPartial() {
      org.example.PaginateInstructorResponse result = new org.example.PaginateInstructorResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.example.PaginateInstructorResponse result) {
      if (instructorsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          instructors_ = java.util.Collections.unmodifiableList(instructors_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.instructors_ = instructors_;
      } else {
        result.instructors_ = instructorsBuilder_.build();
      }
    }

    private void buildPartial0(org.example.PaginateInstructorResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.pageNumber_ = pageNumber_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.perPage_ = perPage_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.pageCount_ = pageCount_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.totalCount_ = totalCount_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.PaginateInstructorResponse) {
        return mergeFrom((org.example.PaginateInstructorResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.PaginateInstructorResponse other) {
      if (other == org.example.PaginateInstructorResponse.getDefaultInstance()) return this;
      if (other.getPageNumber() != 0L) {
        setPageNumber(other.getPageNumber());
      }
      if (other.getPerPage() != 0L) {
        setPerPage(other.getPerPage());
      }
      if (other.getPageCount() != 0L) {
        setPageCount(other.getPageCount());
      }
      if (other.getTotalCount() != 0L) {
        setTotalCount(other.getTotalCount());
      }
      if (instructorsBuilder_ == null) {
        if (!other.instructors_.isEmpty()) {
          if (instructors_.isEmpty()) {
            instructors_ = other.instructors_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureInstructorsIsMutable();
            instructors_.addAll(other.instructors_);
          }
          onChanged();
        }
      } else {
        if (!other.instructors_.isEmpty()) {
          if (instructorsBuilder_.isEmpty()) {
            instructorsBuilder_.dispose();
            instructorsBuilder_ = null;
            instructors_ = other.instructors_;
            bitField0_ = (bitField0_ & ~0x00000010);
            instructorsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getInstructorsFieldBuilder() : null;
          } else {
            instructorsBuilder_.addAllMessages(other.instructors_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              pageNumber_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              perPage_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              pageCount_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              totalCount_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              org.example.Entity.InstructorMetadata m =
                  input.readMessage(
                      org.example.Entity.InstructorMetadata.parser(),
                      extensionRegistry);
              if (instructorsBuilder_ == null) {
                ensureInstructorsIsMutable();
                instructors_.add(m);
              } else {
                instructorsBuilder_.addMessage(m);
              }
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long pageNumber_ ;
    /**
     * <code>int64 page_number = 1;</code>
     * @return The pageNumber.
     */
    @java.lang.Override
    public long getPageNumber() {
      return pageNumber_;
    }
    /**
     * <code>int64 page_number = 1;</code>
     * @param value The pageNumber to set.
     * @return This builder for chaining.
     */
    public Builder setPageNumber(long value) {

      pageNumber_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 page_number = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPageNumber() {
      bitField0_ = (bitField0_ & ~0x00000001);
      pageNumber_ = 0L;
      onChanged();
      return this;
    }

    private long perPage_ ;
    /**
     * <code>int64 per_page = 2;</code>
     * @return The perPage.
     */
    @java.lang.Override
    public long getPerPage() {
      return perPage_;
    }
    /**
     * <code>int64 per_page = 2;</code>
     * @param value The perPage to set.
     * @return This builder for chaining.
     */
    public Builder setPerPage(long value) {

      perPage_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 per_page = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPerPage() {
      bitField0_ = (bitField0_ & ~0x00000002);
      perPage_ = 0L;
      onChanged();
      return this;
    }

    private long pageCount_ ;
    /**
     * <code>int64 page_count = 3;</code>
     * @return The pageCount.
     */
    @java.lang.Override
    public long getPageCount() {
      return pageCount_;
    }
    /**
     * <code>int64 page_count = 3;</code>
     * @param value The pageCount to set.
     * @return This builder for chaining.
     */
    public Builder setPageCount(long value) {

      pageCount_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 page_count = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPageCount() {
      bitField0_ = (bitField0_ & ~0x00000004);
      pageCount_ = 0L;
      onChanged();
      return this;
    }

    private long totalCount_ ;
    /**
     * <code>int64 total_count = 4;</code>
     * @return The totalCount.
     */
    @java.lang.Override
    public long getTotalCount() {
      return totalCount_;
    }
    /**
     * <code>int64 total_count = 4;</code>
     * @param value The totalCount to set.
     * @return This builder for chaining.
     */
    public Builder setTotalCount(long value) {

      totalCount_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int64 total_count = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalCount() {
      bitField0_ = (bitField0_ & ~0x00000008);
      totalCount_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<org.example.Entity.InstructorMetadata> instructors_ =
      java.util.Collections.emptyList();
    private void ensureInstructorsIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        instructors_ = new java.util.ArrayList<org.example.Entity.InstructorMetadata>(instructors_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.example.Entity.InstructorMetadata, org.example.Entity.InstructorMetadata.Builder, org.example.Entity.InstructorMetadataOrBuilder> instructorsBuilder_;

    /**
     * <code>repeated .subject.InstructorMetadata instructors = 5;</code>
     */
    public java.util.List<org.example.Entity.InstructorMetadata> getInstructorsList() {
      if (instructorsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(instructors_);
      } else {
        return instructorsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .subject.InstructorMetadata instructors = 5;</code>
     */
    public int getInstructorsCount() {
      if (instructorsBuilder_ == null) {
        return instructors_.size();
      } else {
        return instructorsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .subject.InstructorMetadata instructors = 5;</code>
     */
    public org.example.Entity.InstructorMetadata getInstructors(int index) {
      if (instructorsBuilder_ == null) {
        return instructors_.get(index);
      } else {
        return instructorsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .subject.InstructorMetadata instructors = 5;</code>
     */
    public Builder setInstructors(
        int index, org.example.Entity.InstructorMetadata value) {
      if (instructorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInstructorsIsMutable();
        instructors_.set(index, value);
        onChanged();
      } else {
        instructorsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .subject.InstructorMetadata instructors = 5;</code>
     */
    public Builder setInstructors(
        int index, org.example.Entity.InstructorMetadata.Builder builderForValue) {
      if (instructorsBuilder_ == null) {
        ensureInstructorsIsMutable();
        instructors_.set(index, builderForValue.build());
        onChanged();
      } else {
        instructorsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .subject.InstructorMetadata instructors = 5;</code>
     */
    public Builder addInstructors(org.example.Entity.InstructorMetadata value) {
      if (instructorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInstructorsIsMutable();
        instructors_.add(value);
        onChanged();
      } else {
        instructorsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .subject.InstructorMetadata instructors = 5;</code>
     */
    public Builder addInstructors(
        int index, org.example.Entity.InstructorMetadata value) {
      if (instructorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInstructorsIsMutable();
        instructors_.add(index, value);
        onChanged();
      } else {
        instructorsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .subject.InstructorMetadata instructors = 5;</code>
     */
    public Builder addInstructors(
        org.example.Entity.InstructorMetadata.Builder builderForValue) {
      if (instructorsBuilder_ == null) {
        ensureInstructorsIsMutable();
        instructors_.add(builderForValue.build());
        onChanged();
      } else {
        instructorsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .subject.InstructorMetadata instructors = 5;</code>
     */
    public Builder addInstructors(
        int index, org.example.Entity.InstructorMetadata.Builder builderForValue) {
      if (instructorsBuilder_ == null) {
        ensureInstructorsIsMutable();
        instructors_.add(index, builderForValue.build());
        onChanged();
      } else {
        instructorsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .subject.InstructorMetadata instructors = 5;</code>
     */
    public Builder addAllInstructors(
        java.lang.Iterable<? extends org.example.Entity.InstructorMetadata> values) {
      if (instructorsBuilder_ == null) {
        ensureInstructorsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, instructors_);
        onChanged();
      } else {
        instructorsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .subject.InstructorMetadata instructors = 5;</code>
     */
    public Builder clearInstructors() {
      if (instructorsBuilder_ == null) {
        instructors_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        instructorsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .subject.InstructorMetadata instructors = 5;</code>
     */
    public Builder removeInstructors(int index) {
      if (instructorsBuilder_ == null) {
        ensureInstructorsIsMutable();
        instructors_.remove(index);
        onChanged();
      } else {
        instructorsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .subject.InstructorMetadata instructors = 5;</code>
     */
    public org.example.Entity.InstructorMetadata.Builder getInstructorsBuilder(
        int index) {
      return getInstructorsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .subject.InstructorMetadata instructors = 5;</code>
     */
    public org.example.Entity.InstructorMetadataOrBuilder getInstructorsOrBuilder(
        int index) {
      if (instructorsBuilder_ == null) {
        return instructors_.get(index);  } else {
        return instructorsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .subject.InstructorMetadata instructors = 5;</code>
     */
    public java.util.List<? extends org.example.Entity.InstructorMetadataOrBuilder> 
         getInstructorsOrBuilderList() {
      if (instructorsBuilder_ != null) {
        return instructorsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(instructors_);
      }
    }
    /**
     * <code>repeated .subject.InstructorMetadata instructors = 5;</code>
     */
    public org.example.Entity.InstructorMetadata.Builder addInstructorsBuilder() {
      return getInstructorsFieldBuilder().addBuilder(
          org.example.Entity.InstructorMetadata.getDefaultInstance());
    }
    /**
     * <code>repeated .subject.InstructorMetadata instructors = 5;</code>
     */
    public org.example.Entity.InstructorMetadata.Builder addInstructorsBuilder(
        int index) {
      return getInstructorsFieldBuilder().addBuilder(
          index, org.example.Entity.InstructorMetadata.getDefaultInstance());
    }
    /**
     * <code>repeated .subject.InstructorMetadata instructors = 5;</code>
     */
    public java.util.List<org.example.Entity.InstructorMetadata.Builder> 
         getInstructorsBuilderList() {
      return getInstructorsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.example.Entity.InstructorMetadata, org.example.Entity.InstructorMetadata.Builder, org.example.Entity.InstructorMetadataOrBuilder> 
        getInstructorsFieldBuilder() {
      if (instructorsBuilder_ == null) {
        instructorsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.example.Entity.InstructorMetadata, org.example.Entity.InstructorMetadata.Builder, org.example.Entity.InstructorMetadataOrBuilder>(
                instructors_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        instructors_ = null;
      }
      return instructorsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:subject.PaginateInstructorResponse)
  }

  // @@protoc_insertion_point(class_scope:subject.PaginateInstructorResponse)
  private static final org.example.PaginateInstructorResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.PaginateInstructorResponse();
  }

  public static org.example.PaginateInstructorResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PaginateInstructorResponse>
      PARSER = new com.google.protobuf.AbstractParser<PaginateInstructorResponse>() {
    @java.lang.Override
    public PaginateInstructorResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PaginateInstructorResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PaginateInstructorResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.PaginateInstructorResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

