// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subject.proto

package org.example;

public interface UpdateSubjectRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:subject.UpdateSubjectRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string subject_id = 2;</code>
   * @return The subjectId.
   */
  java.lang.String getSubjectId();
  /**
   * <code>string subject_id = 2;</code>
   * @return The bytes for subjectId.
   */
  com.google.protobuf.ByteString
      getSubjectIdBytes();

  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int64 semester = 4;</code>
   * @return The semester.
   */
  long getSemester();

  /**
   * <code>int64 year = 5;</code>
   * @return The year.
   */
  long getYear();

  /**
   * <code>string faculty = 6;</code>
   * @return The faculty.
   */
  java.lang.String getFaculty();
  /**
   * <code>string faculty = 6;</code>
   * @return The bytes for faculty.
   */
  com.google.protobuf.ByteString
      getFacultyBytes();

  /**
   * <code>string description = 7;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 7;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>repeated string prerequisites = 8;</code>
   * @return A list containing the prerequisites.
   */
  java.util.List<java.lang.String>
      getPrerequisitesList();
  /**
   * <code>repeated string prerequisites = 8;</code>
   * @return The count of prerequisites.
   */
  int getPrerequisitesCount();
  /**
   * <code>repeated string prerequisites = 8;</code>
   * @param index The index of the element to return.
   * @return The prerequisites at the given index.
   */
  java.lang.String getPrerequisites(int index);
  /**
   * <code>repeated string prerequisites = 8;</code>
   * @param index The index of the value to return.
   * @return The bytes of the prerequisites at the given index.
   */
  com.google.protobuf.ByteString
      getPrerequisitesBytes(int index);

  /**
   * <code>bool is_admin = 99;</code>
   * @return The isAdmin.
   */
  boolean getIsAdmin();
}
