// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subject.proto

package org.example;

public interface UpdateSubjectResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:subject.UpdateSubjectResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.subject.Subject subject = 1;</code>
   * @return Whether the subject field is set.
   */
  boolean hasSubject();
  /**
   * <code>.subject.Subject subject = 1;</code>
   * @return The subject.
   */
  org.example.Entity.Subject getSubject();
  /**
   * <code>.subject.Subject subject = 1;</code>
   */
  org.example.Entity.SubjectOrBuilder getSubjectOrBuilder();
}
