// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: instructor.proto

package org.example;

public interface UpdateInstructorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:subject.UpdateInstructorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string full_name = 2;</code>
   * @return The fullName.
   */
  java.lang.String getFullName();
  /**
   * <code>string full_name = 2;</code>
   * @return The bytes for fullName.
   */
  com.google.protobuf.ByteString
      getFullNameBytes();

  /**
   * <code>string faculty = 3;</code>
   * @return The faculty.
   */
  java.lang.String getFaculty();
  /**
   * <code>string faculty = 3;</code>
   * @return The bytes for faculty.
   */
  com.google.protobuf.ByteString
      getFacultyBytes();

  /**
   * <code>string email = 4;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 4;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string phone_number = 5;</code>
   * @return The phoneNumber.
   */
  java.lang.String getPhoneNumber();
  /**
   * <code>string phone_number = 5;</code>
   * @return The bytes for phoneNumber.
   */
  com.google.protobuf.ByteString
      getPhoneNumberBytes();

  /**
   * <code>string website = 6;</code>
   * @return The website.
   */
  java.lang.String getWebsite();
  /**
   * <code>string website = 6;</code>
   * @return The bytes for website.
   */
  com.google.protobuf.ByteString
      getWebsiteBytes();

  /**
   * <code>string degree = 7;</code>
   * @return The degree.
   */
  java.lang.String getDegree();
  /**
   * <code>string degree = 7;</code>
   * @return The bytes for degree.
   */
  com.google.protobuf.ByteString
      getDegreeBytes();

  /**
   * <code>bool is_admin = 99;</code>
   * @return The isAdmin.
   */
  boolean getIsAdmin();
}
