// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: instructor.proto

package org.example;

public interface UpdateInstructorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:subject.UpdateInstructorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.subject.Instructor instructor = 1;</code>
   * @return Whether the instructor field is set.
   */
  boolean hasInstructor();
  /**
   * <code>.subject.Instructor instructor = 1;</code>
   * @return The instructor.
   */
  org.example.Entity.Instructor getInstructor();
  /**
   * <code>.subject.Instructor instructor = 1;</code>
   */
  org.example.Entity.InstructorOrBuilder getInstructorOrBuilder();
}
