// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subject.proto

package org.example;

public interface ValidateSubjectIdResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:subject.ValidateSubjectIdResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool valid = 1;</code>
   * @return The valid.
   */
  boolean getValid();
}
